services:
  agent-smith:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/logs
    ports: [ "8000:8000" ]

  bwapp:
    image: raesene/bwapp
    ports: [ "8080:80", "3306:3306" ]
