version: '3'

services:
  kali:
    build:
      context: .
    command: |
      "sleep 30"
      "curl bwapp/install.php?install=yes"
    depends_on:
      - bwapp
    volumes:
      - ./app:/root/app
      - ./cves:/root/cves
      - ./db:/root/db
  bwapp:
    image: "raesene/bwapp"
    ports:
      - 8080:80
    expose:
      - 80
  badstore:
    image: "jvhoof/badstore-docker"
    ports:
      - 8081:80
    expose:
      - 80

